/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as carbonCreditNftSol from "./CarbonCreditNFT.sol";
export type { carbonCreditNftSol };
export type { Counter } from "./Counter";
